export const output = [
	{
		name: 'Sticker Twelve',
		id: 'sticker-12',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/012.png',
		emojis: [],
		stats: {
			views: 0,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Two',
		id: 'sticker-2',
		description: 'Sticker 2',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 3,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Four',
		id: 'sticker-4',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/038.png',
		emojis: [],
		stats: {
			views: 1,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Two',
		id: 'sticker-2',
		description: 'Sticker 2',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/036.png',
		emojis: [],
		stats: {
			views: 4,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker One',
		id: 'sticker-1',
		description: 'Sticker 1',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 28,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Ten',
		id: 'sticker-10',
		description: 'Sticker 10',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/036.png',
		emojis: [],
		stats: {
			views: 4,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Two',
		id: 'sticker-2',
		description: 'Sticker 2',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 7,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker One',
		id: 'sticker-1',
		description: 'Sticker 1',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/015.png',
		stats: {
			views: 6,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Twelve',
		id: 'sticker-12',
		description: 'Sticker 12',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/019.png',
		emojis: [],
		stats: {
			views: 42,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Sixteen',
		id: 'sticker-16',
		description: 'Sticker 16',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/032.png',
		emojis: [],
		stats: {
			views: 4,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Eleven',
		id: 'sticker-11',
		description: 'Sticker 11',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 10,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker One',
		id: 'sticker-1',
		description: 'Sticker 1',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/038.png',
		emojis: [],
		stats: {
			views: 16,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Two',
		id: 'sticker-2',
		description: 'Sticker 2',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/019.png',
		emojis: [],
		stats: {
			views: 17,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Twelve',
		id: 'sticker-12',
		description: 'Sticker 12',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 6,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Seventeen',
		id: 'sticker-19',
		description: 'Sticker 17',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 6,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Twenty Nine',
		id: 'sticker-28',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/038.png',
		emojis: [],
		stats: {
			views: 0,
			instagramStories: 0,
		},
	},
	{
		name: 'Heart',
		id: 'sticker-1',
		description: 'A heart with a border and shadow.',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/013.png',
		emojis: ['🍪'],
		stats: {
			views: 84,
			instagramStories: 0,
		},
	},
	{
		name: 'Blushing Corn',
		id: 'blush',
		description: ' ',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/019.png',
		emojis: [],
		stats: {
			views: 46,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Five',
		id: 'sticker-5',
		description: 'Sticker 5',
		source:
			'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/032.png',
		emojis: [],
		stats: {
			views: 19,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Seven',
		id: 'sticker-7',
		description: 'Sticker 7',
		source:
			'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/030.png',
		emojis: [],
		stats: {
			views: 28,
			instagramStories: 0,
		},
	},
	{
		name: '8AM Life',
		id: 'sticker-4',
		description: 'Sticker 4',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/036.png',
		emojis: ['🚂', '🛤️'],
		stats: {
			views: 123,
			instagramStories: 0,
		},
	},
	{
		name: 'Нет',
		id: 'sticker-5',
		description: 'Ну сказал же, нет!',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		stats: {
			views: 7,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker One',
		id: 'sticker-1',
		description: 'Sticker 1',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 15,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Sixteen',
		id: 'sticker-16',
		description: 'Sticker 16',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 2,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Twenty Nine',
		id: 'sticker-29',
		description: 'Sticker 29',
		source:
			'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/012.png',
		emojis: [],
		stats: {
			views: 7,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Thirty',
		id: 'sticker-30',
		description: 'Sticker 30',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/038.png',
		emojis: [],
		stats: {
			views: 37,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Eight',
		id: 'sticker-8',
		description: 'Sticker 8',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/019.png',
		emojis: [],
		stats: {
			views: 14,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Four',
		id: 'sticker-4',
		description: 'Sticker 4',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/014.png',
		emojis: [],
		stats: {
			views: 9,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Two',
		id: 'sticker-2',
		description: 'Sticker 2',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/012.png',
		emojis: [],
		stats: {
			views: 15,
			instagramStories: 0,
		},
	},
	{
		name: "Phil's Bio Eistee Logo",
		id: 'logo',
		description: 'Logo von Phils Bio Eistee',
		source:"https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/023.png",
		emojis: [],
		stats: {
			views: 25,
			instagramStories: 0,
		},
	},
	{
		name: 'Gemini',
		id: 'sticker-3',
		description: 'Sticker 3',
		source:"https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/030.png",
		emojis: [],
		stats: {
			views: 21,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Three',
		id: 'sticker-3',
		description: 'Sticker 3',
		source:
			'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/019.png',
		emojis: [],
		stats: {
			views: 18,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Eight',
		id: 'sticker-8',
		description: 'Sticker 8',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/021.png',
		emojis: [],
		stats: {
			views: 2,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker One',
		id: 'sticker-1',
		description: 'Sticker 1',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/012.png',
		emojis: [],
		stats: {
			views: 4,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Two',
		id: 'sticker-2',
		description: 'Sticker 2',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/040.png',
		emojis: [],
		stats: {
			views: 2,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Twelve',
		id: 'sticker-12',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/012.png',
		emojis: [],
		stats: {
			views: 33,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Three',
		id: 'sticker-3',
		source:"https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/023.png",
		emojis: [],
		stats: {
			views: 8,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker One',
		id: 'sticker-1',
		description: 'Sticker 1',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/021.png',
		emojis: [],
		stats: {
			views: 6,
			instagramStories: 0,
		},
	},
	{
		name: 'Sticker Three',
		id: 'sticker-3',
		description: 'Sticker 3',
		source: 'https://stickershop.line-scdn.net/sticonshop/v1/sticon/60c9984238d2b971e09fa1ff/iPhone/012.png',
		emojis: [],
		stats: {
			views: 3,
			instagramStories: 0,
		},
	},
];
